### ISSUE TITLE
Looking forward to your code.

### ISSUE THREAD

**Issue by qsunyuan** [wangkiw/TEEN#1]
Congratulations on your work for NIPS! 

It incorporates the ideas of prototype learning, mean statistic transfer, and training-free learning paradigms into the FSCIL scenario. 

Looking forward to your open-source code so that we can follow this work.

Thanks.

**Comment by chester-w-xie** [comment]
+1

**Comment by wangkiw** [comment]
Thank you for your attention. The code will be organized and made publicly available soon.

**Comment by wangkiw** [comment]
Sorry for the late update due to other things recently.
